// Temporary portfolio listing data. Keep this independent from the product catalog so
// the future portfolio API can evolve without changing the product feature.
export const portfolioProjects = [
    {
        id: "1",
        eyebrow: "Featured case study",
        category: "Enterprise platform",
        title: "Online Insurance System",
        subtitle: "Digitizing policy, claims and customer operations",
        description: "A connected web, mobile and administration ecosystem created to improve service efficiency and simplify complex insurance workflows.",
        technologies: ["HTML", "CSS", "PHP", "Laravel"],
        industries: ["Insurance", "Finance"],
        image: "/assets/images/Case Study Insurance Image/Case Study Banner.webp",
        imageAlt: "Online insurance platform displayed across multiple devices",
        badge: "Bangladesh · 6 months",
        detailsHref: "/portfolio/1",
        stats: [
            { value: "18", label: "Team members" },
            { value: "6", label: "Months" },
            { value: "3", label: "Connected platforms" },
        ],
    },
    {
        id: "2",
        eyebrow: "Commerce case study",
        category: "E-commerce",
        title: "Beauty Product E-Commerce",
        subtitle: "An integrated retail ecosystem for modern commerce",
        description: "A scalable web and mobile commerce experience that connects catalog, ordering, customer and administration workflows in one platform.",
        technologies: ["React.js", "Node.js", "Flutter", "MongoDB", "AWS"],
        industries: ["E-commerce", "Retail", "Beauty"],
        image: "/assets/images/portfolio/Case Study 2 Image Perfecto/Case Study Banner Perfecto.webp",
        imageAlt: "Beauty product e-commerce platform displayed on desktop and mobile",
        badge: "Bangladesh · 4 months",
        detailsHref: "/portfolio/2",
        stats: [
            { value: "9", label: "Project experts" },
            { value: "4", label: "Months" },
            { value: "5", label: "Core technologies" },
        ],
    },
    {
        id: "3",
        eyebrow: "EdTech case study",
        category: "Learning platform",
        title: "Exam Preparation Platform",
        subtitle: "A focused digital learning and assessment experience",
        description: "A responsive learning platform designed to make examination practice, progress tracking and content administration easier for learners and teams.",
        technologies: ["Flutter", "Laravel", "MySQL"],
        industries: ["Education", "Training", "Assessment"],
        image: "/assets/images/portfolio/Case Study 3/Banner.webp",
        imageAlt: "Exam preparation platform interface",
        badge: "Bangladesh · 6 months",
        detailsHref: "/portfolio/3",
        stats: [
            { value: "8", label: "Team members" },
            { value: "6", label: "Months" },
            { value: "3", label: "Core technologies" },
        ],
    },
    {
        id: "4",
        eyebrow: "Education case study",
        category: "Business application",
        title: "Job & Exam Preparation",
        subtitle: "A smarter learning ecosystem for exam success",
        description: "A custom website and administration panel that centralizes learning content, assessments, subscriptions and operational reporting.",
        technologies: ["PHP", "Laravel", "MySQL", "Bootstrap"],
        industries: ["Education", "Recruitment", "Assessment"],
        image: "/assets/images/portfolio/Casec Study 4/Banner lx.webp",
        imageAlt: "Job and exam preparation website and administration panel",
        badge: "Bangladesh · 4 months",
        detailsHref: "/portfolio/4",
        stats: [
            { value: "7", label: "Team members" },
            { value: "4", label: "Months" },
            { value: "4", label: "Core technologies" },
        ],
    },
];
