// Temporary product catalog. Its shape is intentionally independent from portfolio case studies
// so the product API can replace this module later without coupling the two features.
export const products = [
    {
        id: "insurance-management",
        eyebrow: "Featured product",
        category: "Enterprise solution",
        title: "Insurance Management System",
        subtitle: "A complete digital insurance ecosystem",
        description: "Bring policy sales, claims, customer service and reporting together in one secure platform built for modern insurers.",
        technologies: ["Laravel", "PHP", "MySQL", "REST API"],
        industries: ["Insurance", "Finance", "Enterprise"],
        image: "/assets/images/product/IMS.gif",
        imageAlt: "Insurance management product interface",
        badge: "Secure & scalable",
        liveUrl: "/portfolio/1",
        detailsHref: "/portfolio/1",
        stats: [
            { value: "12", label: "Core modules" },
            { value: "24/7", label: "Secure access" },
            { value: "90%", label: "High usability" },
        ],
    },
    {
        id: "beauty-ecommerce",
        eyebrow: "Commerce product",
        category: "E-commerce",
        title: "Beauty E-Commerce Platform",
        subtitle: "Connected retail across every screen",
        description: "Manage products, inventory, orders, payments and customer experiences through one scalable web and mobile commerce platform.",
        technologies: ["React.js", "Node.js", "Flutter", "AWS"],
        industries: ["E-commerce", "Retail", "Beauty"],
        image: "/assets/images/product/Beauty Business Promotional Post.gif",
        imageAlt: "Beauty e-commerce product interface",
        badge: "Cloud powered",
        liveUrl: "/portfolio/2",
        detailsHref: "/portfolio/2",
        stats: [
            { value: "20K+", label: "Products managed" },
            { value: "100K+", label: "Customers" },
            { value: "99.9%", label: "Platform uptime" },
        ],
    },
    {
        id: "exam-preparation",
        eyebrow: "Learning product",
        category: "EdTech",
        title: "Exam Preparation Platform",
        subtitle: "A smarter learning and assessment experience",
        description: "Give learners an intuitive place to study, practice and track progress while administrators manage content and performance from one dashboard.",
        technologies: ["Laravel", "MySQL", "Bootstrap", "REST API"],
        industries: ["Education", "Training", "Assessment"],
        image: "/assets/images/product/product 3.gif",
        imageAlt: "Exam preparation product interface",
        badge: "Built for growth",
        liveUrl: "/portfolio/4",
        detailsHref: "/portfolio/4",
        stats: [
            { value: "2K+", label: "Active learners" },
            { value: "50K+", label: "Questions" },
            { value: "90%", label: "Less moderation" },
        ],
    },
    {
        id: "job-exam-administration",
        eyebrow: "Administration product",
        category: "Business application",
        title: "Job & Exam Administration System",
        subtitle: "Centralized assessment and subscriber management",
        description: "Organize examination content, subscriptions, rewards and reporting through a centralized administration product designed for growing learning platforms.",
        technologies: ["Laravel", "MySQL", "JavaScript", "REST API"],
        industries: ["Education", "Recruitment", "Assessment"],
        image: "/assets/images/product/product 4.gif",
        imageAlt: "Job and examination administration product interface",
        badge: "Operations ready",
        liveUrl: "/portfolio/4",
        detailsHref: "/portfolio/4",
        stats: [
            { value: "40%", label: "Revenue growth" },
            { value: "60%", label: "Faster operations" },
            { value: "24/7", label: "Learner access" },
        ],
    },
];
