export const softwareProjects = [
    {
        id: 1,
        title: "Insurance Management System",
        subtitle: "A connected platform for policy, claims and customer operations.",
        industry: "Insurance & Finance",
        solutionType: "Custom Enterprise Solution",
        image: "/assets/images/product/IMS.gif",
        stats: [
            { value: "12", label: "Core Modules" },
            { value: "24/7", label: "Secure Access" },
            { value: "90%", label: "High Usability" },
        ],
        features: ["Policy and customer management", "Claims and premium workflows", "Role-based administration", "Reporting and operational analytics"],
        quote: "The platform unified essential insurance operations and gave teams a faster, more reliable way to serve customers.",
    },
    {
        id: 2,
        title: "Beauty E-Commerce Platform",
        subtitle: "Connected retail experiences across web, mobile and administration.",
        industry: "Retail & E-Commerce",
        solutionType: "Web & Mobile Commerce",
        image: "/assets/images/product/Beauty Business Promotional Post.gif",
        stats: [
            { value: "20K+", label: "Products Managed" },
            { value: "100K+", label: "Customers" },
            { value: "99.9%", label: "Platform Uptime" },
        ],
        features: ["Product and inventory management", "Secure checkout and payments", "Mobile-enabled administration", "Customer and sales analytics"],
        quote: "A scalable commerce ecosystem helped the business simplify operations while delivering a consistent customer experience.",
    },
    {
        id: 3,
        title: "Exam Preparation Platform",
        subtitle: "A smarter digital learning, practice and assessment experience.",
        industry: "Education & E-Learning",
        solutionType: "Learning Management Platform",
        image: "/assets/images/product/product 3.gif",
        stats: [
            { value: "2K+", label: "Active Learners" },
            { value: "50K+", label: "Questions" },
            { value: "90%", label: "Less Moderation" },
        ],
        features: ["Personalized examination creation", "Live tests and instant results", "Learning progress analytics", "Community and subscription tools"],
        quote: "The solution made structured exam preparation more accessible, measurable and engaging for learners.",
    },
    {
        id: 4,
        title: "Job & Exam Administration System",
        subtitle: "Centralized content, assessment and subscriber management.",
        industry: "Education Technology",
        solutionType: "Custom Web Application",
        image: "/assets/images/product/product 4.gif",
        stats: [
            { value: "40%", label: "Revenue Growth" },
            { value: "60%", label: "Faster Operations" },
            { value: "24/7", label: "Learner Access" },
        ],
        features: ["Dynamic MCQ management", "Automated examination generation", "Subscriptions and rewards", "Advanced administration and reporting"],
        quote: "A single administration system reduced repetitive work and enabled the platform to scale its learning services.",
    },
];
