const temporaryTrainingImage = "/assets/images/it_Training/Software Development/WhatsApp Image 2023-11-30 at 10.18.36 AM.webp";

export const trainingProjects = [
    {
        id: "skill-development",
        title: "Skill Development of IT Literate Youth",
        subtitle: "Through Artificial Intelligence Technology",
        organization: "Ministry of Youth & Sports",
        location: "Chattogram & Sylhet",
        trainees: "1,200",
        outcome: "Ongoing",
        domains: ["Artificial Intelligence", "Python Programming", "Applied Data Analytics", "Career Readiness"],
        quote: "A practical learning initiative designed to help young people turn technical knowledge into employable skills.",
        image: temporaryTrainingImage,
    },
    {
        id: "asset-project",
        title: "ASSET Project",
        subtitle: "Accelerating and Strengthening Skills for Economic Transformation",
        organization: "Ministry of Education",
        location: "Dhaka",
        trainees: "96",
        outcome: "80% Job Placement",
        domains: ["Web Development with Python", "Graphics Design for Freelancing", "Digital Marketing", "Web Development for Freelancing"],
        quote: "WiztecBD delivered a well-structured and practical training program that helped participants gain real-world skills.",
        image: temporaryTrainingImage,
    },
    {
        id: "deied-project",
        title: "Digital Entrepreneurship and Innovation Ecosystem Development",
        subtitle: "Advanced technology training for emerging digital professionals",
        organization: "Bangladesh Hi-Tech Park Authority",
        location: "Dhaka, Khulna, Rajshahi & Sylhet",
        trainees: "300",
        outcome: "85% Job Placement",
        domains: ["Fourth Industrial Revolution", "Cloud Computing", "Software Engineering", "Professional Certification"],
        quote: "Industry-focused delivery connected technical knowledge with practical projects and career opportunities.",
        image: temporaryTrainingImage,
    },
    {
        id: "ledp-project",
        title: "Learning & Earning Development Project",
        subtitle: "Building sustainable freelancing and digital capabilities",
        organization: "ICT Division",
        location: "Multiple districts across Bangladesh",
        trainees: "550",
        outcome: "82% Positive Outcome",
        domains: ["Web Design", "Digital Marketing", "Graphics Design", "Freelancing Marketplace"],
        quote: "Learners developed market-ready skills through guided practice, mentoring and outcome-focused instruction.",
        image: temporaryTrainingImage,
    },
    {
        id: "mobile-games-project",
        title: "Mobile Games & Apps Development Training",
        subtitle: "Hands-on application and game development for young innovators",
        organization: "ICT Division",
        location: "Dhaka",
        trainees: "700",
        outcome: "88% Completion",
        domains: ["Android Development", "Cross-platform Apps", "Game Design", "Project Deployment"],
        quote: "A hands-on program that enabled participants to transform their ideas into working mobile products.",
        image: temporaryTrainingImage,
    },
];
