export const trainingAreas = [
    {
        id: "software-web-development",
        number: "01",
        title: "Software & Web Development",
        headline: "Build Modern Digital Solutions",
        icon: "code",
        topics: ["Web Development", "Python Web Development", "Web Development for Freelancing", "Software Development"],
        evidence: "The ASSET portfolio includes Web Development with Python Level 4 and Web Development for Freelancing Level 3.",
        cta: "Explore Software Training",
    },
    {
        id: "mobile-app-development",
        number: "02",
        title: "Mobile App Development",
        headline: "Build Applications for a Connected World",
        icon: "mobile",
        topics: ["Cross-Platform Mobile Development", "Mobile Application Development", "Mobile App & Game Development"],
        evidence: "Our profile includes a 700-person cross-platform mobile application development assignment and an EDGE mobile-app development program.",
        cta: "Explore Mobile Training",
    },
    {
        id: "artificial-intelligence",
        number: "03",
        title: "Artificial Intelligence & Machine Learning",
        headline: "Develop Skills for the AI-Driven Economy",
        icon: "cpu",
        topics: ["Artificial Intelligence", "Machine Learning", "AI Professional", "AI Expert", "Applied AI Technologies"],
        evidence: "AI appears across our training portfolio, including the 1,200-participant youth program, the DEIED 4IR program and an EDGE Hire & Train assignment.",
        cta: "Explore AI Training",
    },
    {
        id: "data-analytics",
        number: "04",
        title: "Data Analytics & Business Intelligence",
        headline: "Turn Data Into Decisions",
        icon: "analytics",
        topics: ["Data Analytics", "Power BI Data Analyst", "Data-Driven Business Skills"],
        evidence: "Both Data Analytics and Power BI are represented in our 4IR training portfolio.",
        cta: "Explore Data Training",
    },
    {
        id: "automation-4ir",
        number: "05",
        title: "Automation, Embedded Systems & 4IR",
        headline: "Prepare for the Technologies Shaping Industry 4.0",
        icon: "automation",
        topics: [
            "Embedded Systems",
            "Schematic & Circuit Design",
            "Microcontroller Embedded C Programming",
            "Automation 360",
            "Robotic Process Automation",
            "Machine Learning",
            "Artificial Intelligence",
            "Enterprise IT Governance",
            "Information Systems Security",
        ],
        evidence: "These domains are directly represented in the DEIED 4IR training assignment.",
        cta: "Explore 4IR Training",
        featured: true,
    },
    {
        id: "cloud-emerging-technologies",
        number: "06",
        title: "Cloud & Emerging Technologies",
        icon: "cloud",
        topics: ["Cloud Computing", "Emerging Technology Fundamentals", "AI & Cloud-Based Skills"],
        evidence: "Our EDGE portfolio includes an AI and Cloud Computing Hire & Train program.",
    },
    {
        id: "digital-creative-freelancing",
        number: "07",
        title: "Digital, Creative & Freelancing Skills",
        icon: "creative",
        topics: ["Digital Marketing", "Graphics Design", "Freelancing", "Graphics & Multimedia"],
        evidence: "These areas appear in both our general training-service portfolio and project experience.",
    },
    {
        id: "digital-literacy",
        number: "08",
        title: "Digital Literacy & Professional Skills",
        icon: "literacy",
        topics: ["Basic Computer Training", "Soft Skills", "Professional Digital Skills"],
        evidence: "Our portfolio includes major Basic Computer Training assignments of 1,500 and 3,000 participants, plus a 60-participant soft-skill program.",
    },
];
